url: "https://www.darkavenuephotography.com" # the base hostname & protocol for your site, e.g. https://example.com

permalink: pretty
template_engine: erb

collections:
  people:
    sort_by: name
    sort_direction: asc
  places:
    sort_by: name
    sort_direction: asc
  things:
    sort_by: name
    sort_direction: asc

# Other options you might want to investigate:
#
# base_path: "/" # the subpath of your site, e.g. /blog. If you set this option,
# ensure you use the `relative_url` helper for all links and assets in your HTML.
# If you're using esbuild for frontend assets, edit `esbuild.config.js` to
# update `publicPath`.

# timezone: America/Los_Angeles
# pagination:
#   enabled: true
